name: Java CI with Maven and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'  # Use temurin instead of adoptopenjdk
          java-package: jdk
          check-latest: false

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t librarysystem .

      - name: Run tests with Maven
        run: mvn test

      - name: Run PIT Mutation Testing
        run: mvn org.pitest:pitest-maven:mutationCoverage

